sudo: false

language: node_js

node_js:
  - 6
  - 8
  - 10

notifications:
  email: false

addons:
  code_climate:
    repo_token:

script: npm run coverage

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
